/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flashcards;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

/**
 *
 * @author DylanCarfley
 */
public class DisplayCards extends javax.swing.JFrame {

    static ArrayList<cardClass> cards = new ArrayList<>();
    static FileSystem fs;
    static Path pathToFile; //access to the file
    static File theFile; //file operations like create, delete
    static BasicFileAttributes attributes;
    static BufferedReader tempReader; // reads the file one line at a time, caches upcoming lines
    static InputStream tempIn = null;
    static int index = 0, current = 0, Cardnum = 1;
    Image openFile;
    Toolkit tools;
    Random rand = new Random();

    /**
     * Creates new form DisplayCards
     */
    public void loadImages() {
        openFile = tools.getImage(getClass().getResource("openFile.png"));
    }

    public ImageIcon getImage(Image theImage) {
        Image scaledAlblum = theImage.getScaledInstance(20, 20, Image.SCALE_FAST);
        return new ImageIcon(scaledAlblum);
    }

    public static void openfile() {
        fs = FileSystems.getDefault();
        pathToFile = fs.getPath("c:\\data\\flashcards.txt");

        try {
            tempIn = Files.newInputStream(pathToFile);
            tempReader = new BufferedReader(new InputStreamReader(tempIn));
        } catch (IOException ex) {
            System.out.println("Cannot open file " + pathToFile.getFileName());
            System.exit(0);//die if file does not open
        }
        cardClass aCard;
        String line;
        try {
            while ((line = tempReader.readLine()) != null) {
                String cardInfo[] = line.split(",");
                aCard = new cardClass();

                try {
                    aCard.setId(Integer.parseInt(cardInfo[0]));
                    aCard.setQuestion(cardInfo[1]);
                    aCard.setAnswer(cardInfo[2]);

                    cards.add(aCard);

                } catch (NumberFormatException numberFormatException) {
                    //do nothing - skip error
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(DisplayCards.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void showRecord() {
        this.cardNumLabel.setText("Card #" + Cardnum + " out of " + cards.size());
        this.cardInfoLabel.setText("<html><body><p>" + cards.get(index).getQuestion() + "</p></body></html>");
        this.sideLabel.setText("Side: Question");
    }

    public DisplayCards() {
        initComponents();
        tools = Toolkit.getDefaultToolkit();

        this.setTitle("Flashcards Program");
        loadImages();
        //put a file open picture for the file open button
        fileOpenMenu.setIcon(getImage(openFile));

        openfile();

        showRecord();
        
        repaint();
        // drawStuff();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
         int y = 22;
        int x = 22;
        g = this.cardPanel.getGraphics();
        g.setColor(Color.WHITE);
        //g.fillRect(0, 0, this.cardPanel.getWidth(), this.cardPanel.getHeight());
        g.setColor(Color.blue);
        for (int i = 0; i < 9; i++) {
            g.drawLine(0, y, this.cardPanel.getWidth(), x);
            x += 20;
            y += 20;
        }
        g.setColor(Color.red);
        g.drawLine(0, 22, this.cardPanel.getWidth(), 22);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        firstButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();
        randButton = new javax.swing.JButton();
        sideLabel = new javax.swing.JLabel();
        cardNumLabel = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        cardInfoLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileOpenMenu = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstButton.setText("|<");
        firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtonActionPerformed(evt);
            }
        });

        prevButton.setText("<");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        nextButton.setText(">");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        lastButton.setText(">|");
        lastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastButtonActionPerformed(evt);
            }
        });

        randButton.setText("Random");
        randButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randButtonActionPerformed(evt);
            }
        });

        sideLabel.setText("Side:");

        cardNumLabel.setText("Card:");

        cardPanel.setBackground(new java.awt.Color(255, 255, 255));
        cardPanel.setMaximumSize(new java.awt.Dimension(350, 150));
        cardPanel.setMinimumSize(new java.awt.Dimension(350, 150));
        cardPanel.setPreferredSize(new java.awt.Dimension(350, 150));
        cardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cardPanelMouseClicked(evt);
            }
        });

        cardInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cardInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout cardPanelLayout = new javax.swing.GroupLayout(cardPanel);
        cardPanel.setLayout(cardPanelLayout);
        cardPanelLayout.setHorizontalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        cardPanelLayout.setVerticalGroup(
            cardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cardInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );

        fileMenu.setText("File");

        fileOpenMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        fileOpenMenu.setText("File Open");
        fileOpenMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileOpenMenuActionPerformed(evt);
            }
        });
        fileMenu.add(fileOpenMenu);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(cardNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(sideLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(firstButton)
                        .addGap(18, 18, 18)
                        .addComponent(prevButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nextButton)
                        .addGap(18, 18, 18)
                        .addComponent(lastButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(randButton)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sideLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstButton)
                    .addComponent(prevButton)
                    .addComponent(nextButton)
                    .addComponent(lastButton)
                    .addComponent(randButton))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileOpenMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileOpenMenuActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));//set initial directory to users home directory
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            //test to make sure it works
            System.out.println("Selected file: " + selectedFile.getAbsolutePath());

            fs = FileSystems.getDefault();
            pathToFile = fs.getPath(selectedFile.getAbsolutePath());
            cardClass aCard;
            String line;
            cards.removeAll(cards);// clear out previous cards from list
            try {
                tempIn = Files.newInputStream(pathToFile);
                tempReader = new BufferedReader(new InputStreamReader(tempIn));

                while ((line = tempReader.readLine()) != null) {
                    String cardInfo[] = line.split(",");
                    aCard = new cardClass();

                    try {
                        aCard.setId(Integer.parseInt(cardInfo[0]));
                        aCard.setQuestion(cardInfo[1]);
                        aCard.setAnswer(cardInfo[2]);

                        cards.add(aCard);
                    } catch (NumberFormatException numberFormatException) {
                        //do nothing - skip error
                    }
                }

                showRecord();
                repaint();

            } catch (IOException ex) {
                System.out.println("Cannot open file " + pathToFile.getFileName());
                System.exit(0);//die if file does not open
            }

        }
    }//GEN-LAST:event_fileOpenMenuActionPerformed

    private void firstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstButtonActionPerformed
        // TODO add your handling code here:
     
        index = 0;
        Cardnum = 1;
        showRecord();
        repaint();
    }//GEN-LAST:event_firstButtonActionPerformed

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
        // TODO add your handling code here:
        if (index > 0) {
            index--;
            Cardnum--;
            showRecord();
            repaint();
        }
    }//GEN-LAST:event_prevButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        if (index < cards.size() - 1) {
            index++;
            Cardnum++;
            showRecord();
            repaint();
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void lastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastButtonActionPerformed
        // TODO add your handling code here:
        index = cards.size() - 1;
        Cardnum = cards.size();
        showRecord();
        repaint();
    }//GEN-LAST:event_lastButtonActionPerformed

    private void randButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randButtonActionPerformed
        // TODO add your handling code here:
        Collections.shuffle(cards);
        //index = rand.nextInt(cards.size()-1);
        showRecord();
        repaint();
    }//GEN-LAST:event_randButtonActionPerformed

    private void cardPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cardPanelMouseClicked
        // TODO add your handling code here:
        if ((this.cardInfoLabel.getText()).equals("<html><body><p>" + cards.get(index).getQuestion() + "</p></body></html>")) {
            this.cardInfoLabel.setText("<html><body><p>" + cards.get(index).getAnswer() + "</p></body></html>");
            this.sideLabel.setText("Side: Answer");

        } else if (this.cardInfoLabel.getText().equals("<html><body><p>" + cards.get(index).getAnswer() + "</p></body></html>")) {
            this.cardInfoLabel.setText("<html><body><p>" + cards.get(index).getQuestion() + "</p></body></html>");
            this.sideLabel.setText("Side: Question");
        }
        repaint();
    }//GEN-LAST:event_cardPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayCards().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cardInfoLabel;
    private javax.swing.JLabel cardNumLabel;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fileOpenMenu;
    private javax.swing.JButton firstButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton lastButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton prevButton;
    private javax.swing.JButton randButton;
    private javax.swing.JLabel sideLabel;
    // End of variables declaration//GEN-END:variables
}
